### PR TITLE
Update readme, v3.0.1

### PR DESCRIPTION
**Pull request by rutgersc**
#43

### CODE REVIEW

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
For docs you might want to link to docs.rs so you don't have to keep them hosted and up to date yourself.

**Comment by rutgersc** [comment]
Amazing, today's technology

**Comment by sdroege** [comment]
This should've been 4.0 because of https://github.com/rutgersc/m3u8-rs/commit/39b52a1d4b734f5cffd7c913bd6b03f0031267c1 .

I'd suggest yanking 3.0.1 from crates.io and releasing this all as 4.0.0.

**Comment by sdroege** [comment]
@rutgersc What should we do here? I can prepare a PR for updating the version but you have to do the releasing / yanking to crates.io as I don't have permissions for that.

**Comment by rutgersc** [comment]
Should have noticed the breaking change, my bad. I've gone ahead and replaced the version already. And you should have the invite for crates.io by now, btw.

**Comment by sdroege** [comment]
Ah indeed. Thanks a lot for cleaning that up and giving me the permissions!

**Pull request merged**
